#===========================================
#   Adam Framework
#===========================================
adam:
  access-key:
    header-name: Adam-AK
    request-name: adamAk
  token:
    header-name: Adam-Token
    request-name: adamToken
  security:
    sign-in:
      lock: false
  status: dev
  version: v1.0

#===========================================
#   Server
#===========================================
server:
  port: 9000
  tomcat:
    uri-encoding: utf-8
#===========================================
#   Spring
#===========================================
spring:
  application:
    name: framework
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/test?zeroDateTimeBehavior=convertToNull&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
#===========================================
#   Mybatis
#===========================================
mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker_str
  configuration:
    cache-enabled: false
